
export const benefitValues = [
  {
    icon: "resources_new/money.svg",
    text: "Spara pengar",
    alt: "Money icon",
    subText:
      "Noggrann kostnadsplanering och smarta designval för att undvika kostsamma misstag och omarbeten.",
  },
  {
    icon: "resources_new/calendar.svg",
    text: "Spara tid",
    alt: "Time icon",
    subText:
      "Effektiva planeringsverktyg och expertvägledning för att snabba upp beslut och genomförande.",
  },
  {
    icon: "resources_new/heart.svg",
    text: "Stressa mindre",
    alt: "Heart icon",
    subText:
      "Realistiska modeller och experter från toppklass hjälper till att eliminera gissningsleken i designprocessen.",
  },
];


export const images: string[] = [
  "resources_new/white_cabinet.jpeg",
  "resources_new/book_case.jpeg",
  "resources_new/brown_mirror.jpeg",
  "resources_new/black_bedroom.jpeg",
  "resources_new/light_dining.jpeg",
  "resources_new/white_pantry.jpeg",
  "resources_new/white_dining.jpeg",
  "resources_new/white_mirror.jpeg",
  "resources_new/new (30).jpeg",
]

export const workImages: string[] = [
  "resources_new/new (1).jpeg",
  "resources_new/new (2).jpeg",
  "resources_new/new (3).jpeg",
  "resources_new/new (4).jpeg",
  "resources_new/new (5).jpeg",
  "resources_new/new (6).jpeg",
  "resources_new/new (7).jpeg",
  "resources_new/new (8).jpeg",
  "resources_new/new (9).jpeg",
  "resources_new/new (10).jpeg",
  "resources_new/new (11).jpeg",
  "resources_new/new (12).jpeg",
  "resources_new/new (13).jpeg",
  "resources_new/new (14).jpeg",
  "resources_new/new (15).jpeg",
  "resources_new/new (16).jpeg",
  "resources_new/new (17).jpeg",
  "resources_new/new (18).jpeg",
  "resources_new/new (19).jpeg",
  "resources_new/new (20).jpeg",
  "resources_new/new (21).jpeg",
  "resources_new/new (22).jpeg",
  "resources_new/new (23).jpeg",
  "resources_new/new (24).jpeg",
  "resources_new/new (25).jpeg",
  "resources_new/new (26).jpeg",
  "resources_new/new (27).jpeg",
  "resources_new/new (28).jpeg",
  "resources_new/new (29).jpeg",
  "resources_new/new (30).jpeg",
  "resources_new/new (31).jpeg",
  "resources_new/new (32).jpeg",
  "resources_new/new (33).jpeg",
  "resources_new/new (34).jpeg",
  "resources_new/new (35).jpeg",
  "resources_new/new (36).jpeg",
  "resources_new/new (37).jpeg",
  "resources_new/new (38).jpeg",
  "resources_new/new (39).jpeg",
  "resources_new/new (40).jpeg",
  "resources_new/new (41).jpeg",
  "resources_new/new (42).jpeg",
  "resources_new/new (43).jpeg",
  "resources_new/new (44).jpeg",
  "resources_new/new (45).jpeg",
  "resources_new/new (46).jpeg",
  "resources_new/new (47).jpeg",
  "resources_new/new (48).jpeg",
  "resources_new/new (49).jpeg",
  "resources_new/new (50).jpeg",
  "resources_new/new (51).jpeg",
]
